In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
path="/content/drive/MyDrive/Colab Notebooks/data.csv"
df = pd.read_csv(path)
print(df.to_string())

In [ ]:
mylist = [10,20,30,'apple',True,8.10]

In [ ]:
mylist.append(30)
mylist.append(40)
print(mylist)

[10, 20, 30, 'apple', True, 8.1, 30, 40]


In [ ]:
reversedList = mylist[::-1]
print(reversedList)

[40, 30, 8.1, True, 'apple', 30, 20, 10]


In [ ]:
dict = {1:'data',2:'information',3:'text'}
dict.pop(3)
dict[3]="features"
dict[1]

'data'

In [ ]:
print(dict)

{1: 'data', 2: 'information', 3: 'features'}


In [ ]:
my_tuple = (1,2,3,'apple','mango')

In [ ]:
numeric_tuple = (10,20,30,40,50)
my_tuple = ('a','b','c')
r1 = numeric_tuple + my_tuple

In [ ]:
set1 = {'apple','banana','cherry'}
set2 = {'google','microsoft','apple'}
x = set1.union(set2)
y = set1.intersection(set2)
z = set1.difference(set2)
print(x,'\n',y,'\n',z)

{'microsoft', 'cherry', 'google', 'apple', 'banana'} 
 {'apple'} 
 {'banana', 'cherry'}


In [ ]:
import numpy as np
matrix = np.arange(2,11).reshape(3,3)
print(matrix)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
arr = np.array([1,2,3,4])
arr1 = arr.astype('float')
print(arr1)

[1. 2. 3. 4.]


In [ ]:
arr = np.array([10,20,30])
arr1 = np.array([40,50,60,70,80,90])
arr2 = np.concatenate((arr,arr1))
print(arr2)

[10 20 30 40 50 60 70 80 90]


In [ ]:
arr = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
sumArray = arr+arr2
print(sumArray)

[ 6  8 10 12]


In [ ]:
array1 = np.linspace(10,90,9).reshape(3,3)
firstRow = array1[:1,:3]
lastRow = array1[2:,:3]
print(array1,'\n')
print(firstRow,'\n')
print(lastRow)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] 

[[10. 20. 30.]] 

[[70. 80. 90.]]
